### ISSUE TITLE
Chapters cannot be compiled independently

### ISSUE THREAD

**Issue by rschuetzler** [rschuetzler/datacom-labs#1]
Ideally, each chapter could be compiled independent of the full book (e.g., for posting as assignments). Currently, the placement of the `:imagesdir:` is relative to where you are compiling, so it will work for one or the other, but not both.

**Comment by mojavelinux** [comment]
This should now be possible. This is one of the challenges of having documents act as both include files and standalone documents. But with preprocessor conditionals (and other tricks) it's possible to configure the environment for both scenarios.

**Comment by rschuetzler** [comment]
Fixed in #4
